import "./globals.css";
import { Menu } from "./components/Menu";
import { Inter } from "next/font/google";
import { ContactButton } from "./components/ButtonContact";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContactButton />
        <Menu />
        {children}
      </body>
    </html>
  );
}
